extends Node

var assets := []
enum piece_names {
	WHITE_PRAWN = 0,
	WHITE_KNIGHT,
	WHITE_ROOK,
	WHITE_BISHOP,
	WHITE_KING,
	WHITE_CARP,
	WHITE_TIME_LORD,
	WHITE_REVERSE_PRAWN,
	WHITE_THIS_IS_FINE_DOG,
	WHITE_WEEPING_ANGEL,
	WHITE_CTHULHU,
	WHITE_MR_MEESEEKS,
	WHITE_TELEPORTING_PACIFIST,
	WHITE_CONTRARIAN,
	WHITE_OPPORTUNIST,
	WHITE_HYPNOTIST,
	WHITE_AVENGER,
	WHITE_ORPHAN,
	WHITE_BFF,
	WHITE_ALFRED_HITCHCOCK,
	WHITE_BISHOP_KICKER,
	WHITE_COMMUNIST,
	WHITE_JURONG_WEST_BLOCK_498,
	WHITE_SUMO_WRESTLER,
	WHITE_COUNT_OLAF,
	WHITE_ROYAL_GUARD,
	WHITE_SPIDER,
	WHITE_COVID_19,
	WHITE_ALLIGATOR,
	WHITE_HAYAO_MIYAZAKI,
	WHITE_KUMAR,
	WHITE_VICTIM_OLYMPICS,
	WHITE_AMAZON_PRIME,
	WHITE_SUICIDE_BOMBER,
	WHITE_DOWNTOWN_LINE,
	WHITE_SPY,
	WHITE_JAILER,
	WHITE_LAWYER,
	WHITE_SNIPER_FROM_SWITZERLAND,
	WHITE_RUSSIAN_HACKER,
	WHITE_PIKMIN,
	WHITE_MERCUTIO,
	WHITE_ZARYA,
	WHITE_GEGE_AKUTAMI,
	WHITE_AOI_TODO,
	WHITE_GOJO_SATORU,
	WHITE_SUGURU_GETO,
	WHITE_SHOKO_IEIRI,
	WHITE_FATHER_WHO_BET_ON_GERMANY,
	BLACK_PRAWN, 
	BLACK_KNIGHT,
	BLACK_ROOK,
	BLACK_BISHOP,
	BLACK_KING,
	BLACK_CARP,
	BLACK_TIME_LORD,
	BLACK_REVERSE_PRAWN,
	BLACK_THIS_IS_FINE_DOG,
	BLACK_WEEPING_ANGEL,
	BLACK_CTHULHU,
	BLACK_MR_MEESEEKS,
	BLACK_TELEPORTING_PACIFIST,
	BLACK_CONTRARIAN,
	BLACK_OPPORTUNIST,
	BLACK_HYPNOTIST,
	BLACK_AVENGER,
	BLACK_ORPHAN,
	BLACK_BFF,
	BLACK_ALFRED_HITCHCOCK,
	BLACK_BISHOP_KICKER,
	BLACK_COMMUNIST,
	BLACK_JURONG_WEST_BLOCK_498,
	BLACK_SUMO_WRESTLER,
	BLACK_COUNT_OLAF,
	BLACK_ROYAL_GUARD,
	BLACK_SPIDER,
	BLACK_COVID_19,
	BLACK_ALLIGATOR,
	BLACK_HAYAO_MIYAZAKI,
	BLACK_KUMAR,
	BLACK_VICTIM_OLYMPICS,
	BLACK_AMAZON_PRIME,
	BLACK_SUICIDE_BOMBER,
	BLACK_DOWNTOWN_LINE,
	BLACK_SPY,
	BLACK_JAILER,
	BLACK_LAWYER,
	BLACK_SNIPER_FROM_SWITZERLAND,
	BLACK_RUSSIAN_HACKER,
	BLACK_PIKMIN,
	BLACK_MERCUTIO,
	BLACK_ZARYA,
	BLACK_GEGE_AKUTAMI,
	BLACK_AOI_TODO,
	BLACK_GOJO_SATORU,
	BLACK_SUGURU_GETO,
	BLACK_SHOKO_IEIRI,
	BLACK_FATHER_WHO_BET_ON_GERMANY
}

# Called when the node enters the scene tree for the first time.
func _ready():
	assets.append("res://asset/piece/white/white_prawn.png")
	assets.append("res://asset/piece/white/white_knight.png")
	assets.append("res://asset/piece/white/white_rook.png")
	assets.append("res://asset/piece/white/white_bishop.png")
	assets.append("res://asset/piece/white/white_king.png")
	assets.append("res://asset/piece/white/white_carp.png")
	assets.append("res://asset/piece/white/white_time_lord.png")
	assets.append("res://asset/piece/white/white_reverse_prawn.png")
	assets.append("res://asset/piece/white/white_this_is_fine_dog.png")
	assets.append("res://asset/piece/white/white_weeping_angel.png")
	assets.append("res://asset/piece/white/white_cthulhu.png")
	assets.append("res://asset/piece/white/white_mr_meeseeks.png")
	assets.append("res://asset/piece/white/white_teleporting_pacifist.png")
	assets.append("res://asset/piece/white/white_contrarian.png")
	assets.append("res://asset/piece/white/white_opportunist.png")
	assets.append("res://asset/piece/white/white_hypnotist.png")
	assets.append("res://asset/piece/white/white_avenger.png")
	assets.append("res://asset/piece/white/white_orphan.png")
	assets.append("res://asset/piece/white/white_bff.png")
	assets.append("res://asset/piece/white/white_alfred_hitchcock.png")
	assets.append("res://asset/piece/white/white_bishop_kicker.png")
	assets.append("res://asset/piece/white/white_communist.png")
	assets.append("res://asset/piece/white/white_jurong_west_block_498.png")
	assets.append("res://asset/piece/white/white_sumo_wrestler.png")
	assets.append("res://asset/piece/white/white_count_olaf.png")
	assets.append("res://asset/piece/white/white_royal_guard.png")
	assets.append("res://asset/piece/white/white_spider.png")
	assets.append("res://asset/piece/white/white_covid_19.png")
	assets.append("res://asset/piece/white/white_alligator.png")
	assets.append("res://asset/piece/white/white_hayao_miyazaki.png")
	assets.append("res://asset/piece/white/white_kumar.png")
	assets.append("res://asset/piece/white/white_victim_olympics.png")
	assets.append("res://asset/piece/white/white_amazon_prime.png")
	assets.append("res://asset/piece/white/white_suicide_bomber.png")
	assets.append("res://asset/piece/white/white_downtown_line.png")
	assets.append("res://asset/piece/white/white_spy.png")
	assets.append("res://asset/piece/white/white_jailer.png")
	assets.append("res://asset/piece/white/white_lawyer.png")
	assets.append("res://asset/piece/white/white_sniper_from_switzerland.png")
	assets.append("res://asset/piece/white/white_russian_hacker.png")
	assets.append("res://asset/piece/white/white_pikmin.png")
	assets.append("res://asset/piece/white/white_mercutio.png")
	assets.append("res://asset/piece/white/white_zarya.png")
	assets.append("res://asset/piece/white/white_gege_akutami.png")
	assets.append("res://asset/piece/white/white_aoi_todo.png")
	assets.append("res://asset/piece/white/white_gojo_satoru.png")
	assets.append("res://asset/piece/white/white_suguru_geto.png")
	assets.append("res://asset/piece/white/white_shoko_ieiri.png")
	assets.append("res://asset/piece/white/white_father_who_bet_on_germany.png")
	assets.append("res://asset/piece/black/black_prawn.png")
	assets.append("res://asset/piece/black/black_knight.png")
	assets.append("res://asset/piece/black/black_rook.png")
	assets.append("res://asset/piece/black/black_bishop.png")
	assets.append("res://asset/piece/black/black_king.png")
	assets.append("res://asset/piece/black/black_carp.png")
	assets.append("res://asset/piece/black/black_time_lord.png")
	assets.append("res://asset/piece/black/black_reverse_prawn.png")
	assets.append("res://asset/piece/black/black_this_is_fine_dog.png")
	assets.append("res://asset/piece/black/black_weeping_angel.png")
	assets.append("res://asset/piece/black/black_cthulhu.png")
	assets.append("res://asset/piece/black/black_mr_meeseeks.png")
	assets.append("res://asset/piece/black/black_teleporting_pacifist.png")
	assets.append("res://asset/piece/black/black_contrarian.png")
	assets.append("res://asset/piece/black/black_opportunist.png")
	assets.append("res://asset/piece/black/black_hypnotist.png")
	assets.append("res://asset/piece/black/black_avenger.png")
	assets.append("res://asset/piece/black/black_orphan.png")
	assets.append("res://asset/piece/black/black_bff.png")
	assets.append("res://asset/piece/black/black_alfred_hitchcock.png")
	assets.append("res://asset/piece/black/black_bishop_kicker.png")
	assets.append("res://asset/piece/black/black_communist.png")
	assets.append("res://asset/piece/black/black_jurong_west_block_498.png")
	assets.append("res://asset/piece/black/black_sumo_wrestler.png")
	assets.append("res://asset/piece/black/black_count_olaf.png")
	assets.append("res://asset/piece/black/black_royal_guard.png")
	assets.append("res://asset/piece/black/black_spider.png")
	assets.append("res://asset/piece/black/black_covid_19.png")
	assets.append("res://asset/piece/black/black_alligator.png")
	assets.append("res://asset/piece/black/black_hayao_miyazaki.png")
	assets.append("res://asset/piece/black/black_kumar.png")
	assets.append("res://asset/piece/black/black_victim_olympics.png")
	assets.append("res://asset/piece/black/black_amazon_prime.png")
	assets.append("res://asset/piece/black/black_suicide_bomber.png")
	assets.append("res://asset/piece/black/black_downtown_line.png")
	assets.append("res://asset/piece/black/black_spy.png")
	assets.append("res://asset/piece/black/black_jailer.png")
	assets.append("res://asset/piece/black/black_lawyer.png")
	assets.append("res://asset/piece/black/black_sniper_from_switzerland.png")
	assets.append("res://asset/piece/black/black_russian_hacker.png")
	assets.append("res://asset/piece/black/black_pikmin.png")
	assets.append("res://asset/piece/black/black_mercutio.png")
	assets.append("res://asset/piece/black/black_zarya.png")
	assets.append("res://asset/piece/black/black_gege_akutami.png")
	assets.append("res://asset/piece/black/black_aoi_todo.png")
	assets.append("res://asset/piece/black/black_gojo_satoru.png")
	assets.append("res://asset/piece/black/black_suguru_geto.png")
	assets.append("res://asset/piece/black/black_shoko_ieiri.png")
	assets.append("res://asset/piece/black/black_father_who_bet_on_germany.png")

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
